### ISSUE TITLE
Poetry in the currently deployed 3.10 images is broken

### ISSUE THREAD

**Issue by a-riva** [CircleCI-Public/cimg-python#106]
Running any `poetry` command in `cimg/python:3.10*` images currently deployed on DockerHub fails with this error:

```
$ poetry --version
Traceback (most recent call last):
  File "/home/circleci/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/home/circleci/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/circleci/.poetry/lib/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

The maintainers should release a new version of the 3.10 images that includes https://github.com/CircleCI-Public/cimg-python/commit/8367a3b358813e8e3cb7a801c29bca5f9966a0fb (when building the 3.10 images locally, `poetry` works fine).

**Comment by felicianotech** [comment]
This should be available now.
