### ISSUE TITLE
`pip install` prompts for username yet I have `.netrc` file in my home directory

### ISSUE THREAD

**Issue by 0xabdi** [CircleCI-Public/cimg-python#140]
Hi,

I am trying to run the below script on the `3.10` version of the executor but it keeps prompting for username yet I have the credentials specified under the `.nterc` file in my home directory (It should load the credentials from this file).

```
#!/bin/bash

echo "machine test.com" > /home/circleci/.netrc
echo "login ${USERNAME}" >> /home/circleci/.netrc
echo "password ${API_TOKEN}" >> /home/circleci/.netrc

pip install <package> --extra-index-url ${DOWNLOAD_URL}
```

Below is the error log when I run the same script on CircleCI Cloud
```
Looking in indexes: https://pypi.org/simple, https://test.com/artifactory/api/pypi/pypi-local/simple
User for test: ERROR: Exception:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
....
....
File "/home/circleci/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 200, in ask_input
    return input(message)
EOFError
WARNING: You are using pip version 22.0.4; however, version 22.2.1 is available.
You should consider upgrading via the '/home/circleci/.pyenv/versions/3.10.5/bin/python3.10 -m pip install --upgrade pip' command.

Exited with code exit status 2
CircleCI received exit code 2
```

Strangely enough, when I do `docker pull` of the same image into my local machine and run the same script, it runs without issues.

**Comment by 0xabdi** [comment]
Found the root cause of the issue. The env vars $USERNAME and $PASSWORD were being passed to `.netrc` as-is without being read correctly from CircleCI's context.
